
from flask_admin.contrib.sqla import ModelView
from flask_admin.form import SecureForm
from flask import abort, current_app, flash, redirect, request, url_for, Markup


class MyModelView(ModelView):
    """
    Customized model view for Flask-Admin page (for database tables)
    https://flask-admin.readthedocs.io/en/latest/introduction/#
    """

    # Custom templates
    list_template = 'list_custom.html'
    create_template = 'create_custom.html'
    edit_template = 'edit_custom.html'

    # To add CSRF protection to the forms that are generated by ModelView instances, 
    # use the SecureForm class in your ModelView subclass by specifying the form_base_class parameter
    form_base_class = SecureForm

    # To disable some of the CRUD operations, set any of these boolean parameters
    can_create = True
    can_edit = True
    can_delete = True # disable record deletion
    can_set_page_size = True
    page_size = 12  # the number of entries to display on the list view

    # To enable csv export of the model view
    can_export = True

    # If your model has too much data to display in the list view, you can add a read-only details view by setting
    can_view_details = True

    # Or, have the add & edit forms display inside a modal window on the list page, instead of the dedicated create & edit pages
    # These are popup windows that focus your attention when 
    # editing or creating table records. I think they're cool
    # create_modal = True
    # edit_modal = True


class PowerUnitView(MyModelView):
    """Flask-Admin view for PowerUnit model (public.power_units table)"""

    # # Removing columns from the list view is easy, just pass a list of column names for the column_excludes_list parameter
    # column_exclude_list = ['password_hash', ]
    can_create = True 
    can_edit = True
    can_delete = True # disable record deletion
    column_display_pk = False
    # column_hide_backrefs = False
     
    # form_widget_args = {
    #     'power_unit': {
    #         'rows': 10,
    #         'style': 'color: black'
    #     }
    # }

    def _power_unit_formatter(view, context, model, name):
        # return Markup(f'<a href="https://myijack.com">{model.power_unit}</a>')
            # <span style="background-color: yellow">
        m = Markup(f"""
                <strong>{model.power_unit}</strong>
        """)
        return m

    column_formatters = {
       'power_unit': _power_unit_formatter
    }

    column_list = ('power_unit', 'notes', )
    column_default_sort = 'power_unit'
    column_sortable_list = column_list
    can_set_page_size = True
    page_size = 12  # the number of entries to display on the list view

    # Control the order of the columns in the forms
    form_columns = ('power_unit', 'notes', )

    # To make columns searchable, or to use them for filtering, specify a list of column names:
    # Can't add 'customers' or 'structures' to the following list (not sure why, but maybe something to do with it being a backref/relationship field)
    column_searchable_list = ('power_unit', 'notes', )
    # column_filters = ('gateway')

    # For a faster editing experience, enable inline editing in the list view:
    # Won't work if you add 'gateway' to this list since 'gateway' is the primary key
    column_editable_list = ('power_unit', 'notes', )

    column_labels = dict(
        power_unit="Power Unit Serial", 
        notes="Notes", 
    )


class PowerUnitMetaView(MyModelView):
    """Flask-Admin view for PowerUnitMeta model (public.power_units_meta table)"""

    # # Removing columns from the list view is easy, just pass a list of column names for the column_excludes_list parameter
    # column_exclude_list = ['password_hash', ]
    can_create = True 
    can_edit = True
    can_delete = True # disable record deletion
    column_display_pk = True
    # column_hide_backrefs = False

    column_list = ('id', 'id_foreign', 'element', 'power_unit', 'notes', )
    column_default_sort = 'power_unit'
    column_sortable_list = column_list
    can_set_page_size = True
    page_size = 12  # the number of entries to display on the list view

    # Control the order of the columns in the forms
    form_columns = ('element', 'id_foreign', 'power_unit', 'notes', )
    form_choices = {'element': [('0', 'text color'), ('1', 'fill color')]}

    # To make columns searchable, or to use them for filtering, specify a list of column names:
    # Can't add 'customers' or 'structures' to the following list (not sure why, but maybe something to do with it being a backref/relationship field)
    column_searchable_list = ('id', 'id_foreign', 'element', 'power_unit', 'notes', )
    # column_filters = ('gateway')

    # For a faster editing experience, enable inline editing in the list view:
    # Won't work if you add 'gateway' to this list since 'gateway' is the primary key
    column_editable_list = ('element', 'id_foreign', 'power_unit', 'notes', )

    column_labels = dict(
        id_foreign="Foreign ID",
        power_unit="Power Unit Serial", 
        notes="Notes", 
    )
    column_descriptions = dict(
        id_foreign="The foreign ID (e.g. ID of the actual 'power_unit')",
        element="The element to style (e.g. 'text color' or 'fill color'",
        power_unit="Name of power unit", 
    )