version: '3.7'
services:
  flask_admin_dev:
    volumes:
      # Mount the root folder that contains .git
      - ..:/workspace
    build:
      # context: where should docker-compose look for the Dockerfile?
      # i.e. either a path to a directory containing a Dockerfile, or a url to a git repository
      context: ..
      dockerfile: Dockerfile.dev
    # env_file: 
    #   - ../.env
    # environment:
    #   FLASK_CONFIG: development
    # Forwards port 0.0.0.0:5005 from the Docker host (e.g. Windows desktop) to the dev environment container's port 5000
    user: user
    ports:
      - 0.0.0.0:5005:5005
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity